name: fitquest_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.1.0

  # Storage & Utilities
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  percent_indicator: ^4.2.3

  # UI Icons
  cupertino_icons: ^1.0.2

  google_fonts: ^6.1.0

  # Camera & Pose Detection
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.11.0

  # Image Picker (for body scan photos)
  image_picker: ^1.0.7

  # Pedometer (step counter)
  pedometer: ^4.0.0

  # Runtime permissions
  permission_handler: ^11.3.1

  # Charts (analytics screen)
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true